service: my-express-application

custom:
  tableName: 'remote-machine-pings-table-${self:provider.stage}'

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["RemoteMachinePingsDynamoDBTable", "Arn" ] }
  environment:
    REMOTE_MACHINE_PINGS_TABLE: ${self:custom.tableName}

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  getMachine:
    handler: index.handler
    events:
      - http: 'GET /machines/{proxy+}'
  createMachine:
    handler: index.handler
    events:
      - http: 'POST /machines'

resources:
  Resources:
    RemoteMachinePingsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: machineId
            AttributeType: S
        KeySchema:
          -
            AttributeName: machineId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}